### ISSUE TITLE
The version of CRD and community-operator is not synchronized

### ISSUE THREAD

**Issue by kevin85421** [mongodb/helm-charts#122]
**What did you do to encounter the bug?**
```sh
# Step1: Install community-operator & CRD
cd community-operator
mkdir charts
cd charts
cd ..
ln -s ../../community-operator-crds .
helm install community-operator .

# Step2: Create a custom resource (CR.yaml is shown as follows.)
kubectl apply -f CR.yaml

# Step3: Check CR status
kubectl get mdbc

# Step3 output => No phase and version! => BUG
# NAME                           PHASE     VERSION
# example-mongodb     

# Step4: Check secrets
kubectl get secrets

# Secret "example-mongodb-admin-my-user" has not been created. => BUG

# Step5: Check operator log
kubectl logs <mongodb-operator-pod>
```

* CR.yaml
```
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
 name: example-mongodb
spec:
 members: 1
 type: ReplicaSet
 version: "4.2.6"
 security:
   authentication:
     modes: ["SCRAM"]
 users:
   - name: my-user
     db: admin
     passwordSecretRef: # a reference to the secret that will be used to generate the user's password
       name: my-user-password
     roles:
       - name: clusterAdmin
         db: admin
       - name: userAdminAnyDatabase
         db: admin
     scramCredentialsSecretName: my-scram
 additionalMongodConfig:
   storage.wiredTiger.engineConfig.journalCompressor: zlib

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
 name: my-user-password
type: Opaque
stringData:
 password: uiucxlab

```

**What did you expect?**
* Step3
![截圖 2022-03-05 下午9 19 57](https://user-images.githubusercontent.com/20109646/156907817-59892e22-15c7-4b01-9efb-5fb08edc43d9.png)
* Step4
![截圖 2022-03-05 下午9 20 35](https://user-images.githubusercontent.com/20109646/156907806-a0b16dc7-0f8a-4cb8-8df5-fec98d26c2ff.png)

**What happened instead?**
* Step3
![截圖 2022-03-05 下午8 21 49](https://user-images.githubusercontent.com/20109646/156906497-3f9cfc95-dd6f-48e6-8684-29bb1cc59167.png)
* Step4
![截圖 2022-03-05 下午8 22 22](https://user-images.githubusercontent.com/20109646/156906503-1764d066-389d-43fd-ad02-a5119f774165.png)
* Step5
![截圖 2022-03-05 下午8 23 31](https://user-images.githubusercontent.com/20109646/156906508-6c53c554-eb15-439a-bdd5-cdaed94fc117.png)

**Additional context**
* Solution Reference: https://github.com/mongodb/mongodb-kubernetes-operator/issues/676
