### ISSUE TITLE
Database.yaml file for the Enteprise Operator has incorrect sharding values causing the database to not run

### ISSUE THREAD

**Issue by kwill4026** [mongodb/helm-charts#127]
**What did you do to encounter the bug?**
1. Git clone the repo to my desktop
2. Set the mongodb.type to Sharded Cluster and ran **helm install sharding --debug --dry-run -f values.yaml .**
3. See the computed values below with mongodsPerShardCount and mongosCount showing no value: 
```
# Source: enterprise-database/templates/database.yaml
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: sharding
  namespace: test
spec:
  type: ShardedCluster
  shardCount: 2
  mongodsPerShardCount:
  mongosCount:
  configServerCount: 3
  version: 5.0.5-ent
  persistent: false
  exposedExternally: true
```
This is because of incorrect spelling of mongos and mongodbsPerShardCount.....see below: 
```
mongodsPerShardCount: {{ .Values.mongodb.sharding.mongodbsPerShardCount }}
mongosCount: {{ .Values.mongodb.sharding.monosCount }}
```

**What did you expect?**
I expected the chart to run the sharded cluster with a mongos, configserver, and shard. 

**What happened instead?**
Instead only the config server runs and not the other shard resources. 
See below as only config runs but the mongos and shard pods cannot. 
```
NAME                    READY   STATUS    RESTARTS   AGE
pod/sharding-config-0   1/1     Running   0          2m9s
pod/sharding-config-1   1/1     Running   0          102s
pod/sharding-config-2   1/1     Running   0          85s

NAME                            TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)           AGE
service/sharding-cs             ClusterIP   None            <none>        27017/TCP         2m9s
service/sharding-cs-external    NodePort    10.43.145.15    <none>        27017:32466/TCP   2m9s
service/sharding-sh             ClusterIP   None            <none>        27017/TCP         62s
service/sharding-sh-external    NodePort    10.43.246.207   <none>        27017:30049/TCP   62s
service/sharding-svc            ClusterIP   None            <none>        27017/TCP         58s
service/sharding-svc-external   NodePort    10.43.239.36    <none>        27017:31580/TCP   58s

NAME                               READY   AGE
statefulset.apps/sharding-0        0/0     62s
statefulset.apps/sharding-1        0/0     62s
statefulset.apps/sharding-config   3/3     2m9s
statefulset.apps/sharding-mongos   0/0     58s
```

**Kubernetes Cluster Information**
```
Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-13+d2965f0db10712", GitCommit:"d2965f0db1071203c6f5bc662c2827c71fc8b20d", GitTreeState:"clean", BuildDate:"2021-06-26T01:02:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.8", GitCommit:"4a3b558c52eb6995b3c5c1db5e54111bd0645a64", GitTreeState:"clean", BuildDate:"2021-12-15T14:46:22Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```
```
Running RKE version: v1.3.6  
```
