### ISSUE TITLE
community-operator: CR created tries to use operator serviceAccount (deployed in other namespace)

### ISSUE THREAD

**Issue by Morriz** [mongodb/helm-charts#144]
**What did you do to encounter the bug?**
1. Deploy without resource first to get crds installed (because of bug #143): 
```
helm install community-operator mongodb/community-operator --namespace mongodb-operator --create-namespace --set operator.watchNamespace=mongodb --set createResource=false,tls.enabled=true
```
2. Same command but set `createResource=true`

**What did you expect?**
Mongo statefulset to start

**What happened instead?**
Errors in creation of statefulset:
```
create Pod mongodb-0 in StatefulSet mongodb failed error: pods "mongodb-0" is forbidden: error looking up service account mongodb/mongodb-database: serviceaccount "mongodb-data base" not found
```

**Screenshots**

**Kubernetes Cluster Information**
 - Digital Ocean
 - Version: 1.22

**Comment by Morriz** [comment]
fixed by changing `templates/database_roles.yaml` to:
```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.database.name }}
  namespace: {{ .Values.resource.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.database.name }}
  namespace: {{ .Values.resource.namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - patch
      - delete
      - get

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.database.name }}
  namespace: {{ .Values.resource.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.database.name }}
roleRef:
  kind: Role
  name: {{ .Values.database.name }}
  apiGroup: rbac.authorization.k8s.io
```
