### ISSUE TITLE
Need a way to add labels to PVCs created by MongoDB

### ISSUE THREAD

**Issue by Ahmad-Faizan** [mongodb/helm-charts#186]
The community operator Helm chart creates PVCs but there is no way to add labels on the PVCs being created.
The reason we want to do this is to exclude the PVCs from being backed up by Velero. Velero expects a label on the resources which don't need to be backed up. To avoid the MongoDB PVC in the backups, we need to add a label to the PVCs.

I found these lines in the CRD definition
https://github.com/mongodb/helm-charts/blob/main/charts/community-operator-crds/templates/mongodbcommunity.mongodb.com_mongodbcommunity.yaml#L319-L328

I want to achieve something like this :
```yaml
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb-faizan-test
  namespace: 
spec:
  members: 3
  type: ReplicaSet
  version: 4.4.0
  statefulSet:
    spec:
      volumeClaimTemplates:
      - metadata:
          labels:
            velero.io/exclude-from-backup: "true"
  security:
    tls:
      enabled: false
    authentication:
      modes: ["SCRAM"]
  users: []
```

If this is already possible from the CRD, and I missed it, please help me in figuring it out.
