### ISSUE TITLE
Is MongoDB Atlas GovCloud Supported - https://cloud.mongodbgov.com/

### ISSUE THREAD

**Issue by gitizenme** [mongodb/helm-charts#198]
Hello,

Is MongoDB Atlas GovCloud supported by the Helm charts?

I'm testing out the Helm chart for use in our AWS EKS environment and would like to deploy to MongoDB Atlas GovCloud, I changed the value of `atlasURI` to:
`atlasURI: https://cloud.mongodbgov.com/` 

Which makes progress in creating the project but fails to deploy the database into that project. 

The main error reported in the logs are:

```
{
"level": "INFO",
"time": "2023-01-20T17:40:07.121Z",
"msg": "Advanced Deployment advanced-cluster doesn't exist in Atlas - creating",
"atlasdeployment": "atlas-operator-test/advanced-cluster"
}
{
"level": "INFO",
"time": "2023-01-20T17:40:07.183Z",
"msg": "Status update",
"atlasdeployment": "atlas-operator-test/advanced-cluster",
"lastCondition": {
"type": "DeploymentReady",
"status": "False",
"lastTransitionTime": null,
"reason": "DeploymentNotCreatedInAtlas",
"message": "POST https://cloud.mongodbgov.com/api/atlas/v1.5/groups/63cad1d8f06fe400ece45b46/clusters: 409 (request \"REGION_UNAVAILABLE\") The selected region [US_WEST_2] is unavailable for use."
}
```

```
{
"level": "INFO",
"time": "2023-01-20T17:40:06.947Z",
"msg": "Reading Atlas API credentials from the AtlasProject Secret atlas-operator-test/atlas-deployment-secret",
"atlasdatabaseuser": "atlas-operator-test/atlas-deployment-admin-user"
}
{
"level": "INFO",
"time": "2023-01-20T17:40:07.078Z",
"msg": "Status update",
"atlasdatabaseuser": "atlas-operator-test/atlas-deployment-admin-user",
"lastCondition": {
"type": "DatabaseUserReady",
"status": "False",
"lastTransitionTime": null,
"reason": "DatabaseUserConnectionSecretsNotCreated",
"message": "GET https://cloud.mongodbgov.com/api/atlas/v1.0/groups/63cad1d8f06fe400ece45b46/serverless: 404 (request \"PROVIDER_UNSUPPORTED\") Provider Serverless not currently supported."
}
```

Detailed log is attached. 

[mongodb-atlas-operator-86495f5956-kpjdl.txt](https://github.com/mongodb/helm-charts/files/10468836/mongodb-atlas-operator-86495f5956-kpjdl.txt)

**Comment by gssbzn** [comment]
>409 (request \"REGION_UNAVAILABLE\") The selected region [US_WEST_2] is unavailable for use

for this error it means that the region you are trying to use is not available for cloud gov, depending on the project settings only regions which are FEDRAMP certified will be available, I recommend you try to use [this CLI command](https://www.mongodb.com/docs/atlas/cli/stable/command/atlas-clusters-availableRegions-list/) or [this API endpoint](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/#tag/Clusters/operation/returnAllCloudProviderRegions) to get the list of available regions for your project

And for this one
> 404 (request \"PROVIDER_UNSUPPORTED\") Provider Serverless not currently supported.

Serverless is currently not available for cloud gov

**Comment by gitizenme** [comment]
I was able to sort out this error with help from MongoDB support, the issue is that GovCloud does not support `M5` configurations. I set the `instanceSize` to `M30` and added several other required parameters. 

The correct configuration is:

```
  - advancedDeploymentSpec:
      clusterType: REPLICASET
      name: test-advanced-cluster
      mongoDBMajorVersion: "6.0"
      replicationSpecs:
        - regionConfigs:
            - electableSpecs:
                instanceSize: M30
                nodeCount: 3
              providerName: AWS
              backingProviderName: AWS
              regionName: US_WEST_2
              priority: 7
```
