### ISSUE TITLE
No kind "MongoDBCommunity" is registered

### ISSUE THREAD

**Issue by Drabuna** [mongodb/helm-charts#209]
**What did you do to encounter the bug?**
Running k3s on Hetzner Cloud.

Installing via:
```
helm repo add mongodb https://mongodb.github.io/helm-charts
helm repo update
helm install mongo-operator mongodb/community-operator --namespace dbs --version 0.7.8
```
Creating mongo instance:

```yaml
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongo
  namespace: dbs
spec:
  members: 3
  type: ReplicaSet
  version: "5.0.6"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: root
      db: admin
      passwordSecretRef:
        name: mongo-root-user
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: mongo-scram
      connectionStringSecretName: mongo-root-connection
  statefulSet:
    spec:
      nodeSelector:
        node-pool: dbs
      volumeClaimTemplates:
        storageClassName: hcloud-volumes
      template:
        nodeSelector:
          node-pool: dbs
        spec:
          volumes:
            storageClassName: hcloud-volumes
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
```

**What did you expect?**
I would expect some pods.

**What happened instead?**
Nothing, no pods or restful sets were created.

`kubectl logs mongodbcommunity/mongo` shows the following error:

```
error: no kind "MongoDBCommunity" is registered for version "mongodbcommunity.mongodb.com/v1" in scheme "pkg/scheme/scheme.go:28"
```

**Additional context**
I've also tried installing CRDs and the operator separately like so:
```
helm install mongo-operator-crd mongodb/community-operator-crds --namespace dbs --version 0.7.8
helm install mongo-operator mongodb/community-operator --namespace dbs --version 0.7.8 --set community-operator-crds.enabled=false
```
But that didn't help.
