### ISSUE TITLE
OpenShift install fails with error : Error creating: pods "mongodb-kubernetes-operator-xxxxx-" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, provider "containerized-data-importer": Forbidden: not usable by user or serviceaccount, spec.containers[0].securityContext.runAsUser: Invalid value: 1000000500: must be in the ranges: [1000730000, 1000739999], 

### ISSUE THREAD

**Issue by ydguala** [mongodb/helm-charts#225]
**What did you do to encounter the bug?**
1. helm repo add mongodb https://mongodb.github.io/helm-charts
2. elm install community-operator mongodb/community-operator --set operator.watchNamespace="*" --namespace mongodb-operator --create-namespace

**What did you expect?**
correct installation of the operator

**What happened instead?**
Deployment with error
```
Error creating: pods "mongodb-kubernetes-operator-xxxxx-" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, provider "containerized-data-importer": Forbidden: not usable by user or serviceaccount, spec.containers[0].securityContext.runAsUser: Invalid value: 1000000500: must be in the ranges: [1000730000, 1000739999], 
```

**Kubernetes Cluster Information**
 - Red Hat OpenShift Cluster Platform
 - 4.10.9

**Additional context**
This is related with the Deployment mongodb-kubernetes-operator trying to run with the user id 2000

```
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 2000
```

https://github.com/mongodb/helm-charts/blob/68aef2e8e4bb6b3b35fbc5a26dfafcbf619f7cf8/charts/community-operator/templates/operator.yaml#L73

Although, you can overcome this granting the service account privileged security context constraint (WARNING This is the most relaxed SCC and should be used only for cluster administration. Grant with caution.):

```
oc adm policy add-scc-to-user privileged system:serviceaccount:mongodb-operator:mongodb-kubernetes-operator
```

**Comment by slaskawi** [comment]
It seems your operator deployment is missing setting `MANAGED_SECURITY_CONTEXT` to `true`. You may read more about this [here](https://github.com/mongodb/mongodb-kubernetes-operator/blob/8c2e684d910ae86b3aa0db52ebb55f15730325d5/docs/deploy-configure.md#deploy-replica-sets-on-openshift).

**Comment by ydguala** [comment]
Great! it works perfectly!

```yaml
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
spec:
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  members: 1
  security:
    authentication:
      ignoreUnknownUsers: true
      modes:
        - SCRAM
  statefulSet:
    spec:
      selector: {}
      serviceName: example-openshift-mongodb-svc
      template:
        spec:
          containers:
            - env:
                - name: MANAGED_SECURITY_CONTEXT
                  value: 'true'
              name: mongodb-agent
            - env:
                - name: MANAGED_SECURITY_CONTEXT
                  value: 'true'
              name: mongod


```
