### ISSUE TITLE
[community-operator] Add support of securityContext for operator pod and container

### ISSUE THREAD

**Issue by legal90** [mongodb/helm-charts#236]
Currently (chart `community-operator v0.8.0`) the securityContext is defined only on the pod level and it can not be customized.
Read more about securityContext: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

In secured and compliant environments it is mandatory to set stricter `securityContext` rules, such as:
- on the container level: 
```yaml
  capabilities:
    drop:
      - ALL
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
```

- on the pod level:
```yaml
  runAsNonRoot: true
  runAsUser: 2000
```

We should implement that in the `community-operator` chart in order to support the customization of these parameters.
