### ISSUE TITLE
podSecurityContext not read in template

### ISSUE THREAD

**Issue by 93imagine** [mongodb/helm-charts#242]
**What did you do to encounter the bug?**
Set the runAsUser value to a different value like: 
```
operator: 
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000960000 
```

**What did you expect?**
This value to overwrite the default. 

**What happened instead?**
A clear and concise description of what happened instead
The value does not get used and the default 2000 is used causing multiple errors like:
`Invalid value: 2000: must be in the ranges: [1000960000, 1000969999]`
