### ISSUE TITLE
community operator 0.9.0 not pushed to helm repo

### ISSUE THREAD

**Issue by jpuskar** [mongodb/helm-charts#291]
Hi. Thanks for your amazing work.

It seems like the community operator "crds" 0.9.0 chart is published, but not the non-crds 0.9.0 chart.

If this is intentional, I apologize for creating an unnecessary github issue.

Note the mismatch in available versions from the command output below.
I ran 'helm repo update mongodb' immediately before running the following command.
My repo url is https://mongodb.github.io/helm-charts
```text
~ % helm search repo mongodb
NAME                                                    CHART VERSION   APP VERSION     DESCRIPTION                                       
mongodb/atlas-cluster                                   0.1.9           0.8.1           A Helm chart to manage Atlas resources with Atl...
mongodb/atlas-deployment                                1.0.1           1.0.0           A Helm chart to manage Atlas resources with Atl...
mongodb/community-operator                              0.8.3           0.8.3           MongoDB Kubernetes Community Operator             
mongodb/community-operator-crds                         0.9.0           0.9.0           MongoDB Kubernetes Community Operator - CRDs      
```

**Comment by legal90** [comment]
I confirm that too 👍  
Also, there is no such tag `community-operator-0.9.0` pushed to the repo. 
Although, the PR is merged https://github.com/mongodb/helm-charts/pull/285
cc @nammn

**Comment by alex-ioma** [comment]
Confirmed by running `helm show chart` after `repo update`: 

```
apiVersion: v2
appVersion: 0.8.3
dependencies:
- condition: community-operator-crds.enabled
  name: community-operator-crds
  repository: https://mongodb.github.io/helm-charts
  version: 0.8.3
description: MongoDB Kubernetes Community Operator
home: https://github.com/mongodb/mongodb-kubernetes-operator
icon: https://mongodb-images-new.s3.eu-west-1.amazonaws.com/leaf-green-dark.png
keywords:
- mongodb
- database
- nosql
kubeVersion: '>=1.16-0'
maintainers:
- email: support@mongodb.com
  name: MongoDB
name: community-operator
type: application
version: 0.8.3
```
