### ISSUE TITLE
statefulset - storageclass values set on values.yaml not considered 

### ISSUE THREAD

**Issue by ajay15283** [mongodb/helm-charts#300]
Hello Team,
 
I am trying to add statefulset related values specifically to add custom storage class name on the values.yaml but it seems to be pick the default values and failing to create pvc which makes pods to pending 

Please find the attached values.yaml 

```yaml
# Deploys MongoDB with `resource` attributes.
createResource: true
resource:
  name: mongodb-replica-set
  version: 4.4.0
  members: 3
  tls:
    enabled: false


    # Installs Cert-Manager in this cluster.
    useX509: false
    sampleX509User: false
    useCertManager: true
    certificateKeySecretRef: tls-certificate
    caCertificateSecretRef: tls-ca-key-pair
    certManager:
      certDuration: 8760h   # 365 days
      renewCertBefore: 720h   # 30 days

  users: []
  # if using the MongoDBCommunity Resource, list any users to be added to the resource
  # users:
  # - name: my-user
  #   db: admin
  #   passwordSecretRef: # a reference to the secret that will be used to generate the user's password
  #     name: <secretName>
  #   roles:
  #     - name: clusterAdmin
  #       db: admin
  #     - name: userAdminAnyDatabase
  #       db: admin
  #     - name: readWriteAnyDatabase
  #       db: admin
  #     - name: dbAdminAnyDatabase
  #       db: admin
  #   scramCredentialsSecretName: my-scram
  statefulSet:
    spec:
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            storageClassName: nfs-csi
        - metadata:
            name: logs-volume
          spec:
            storageClassName: nfs-csi
```
