### ISSUE TITLE
Request: Enable Pod Annotations on the community operator

### ISSUE THREAD

**Issue by meyerkev** [mongodb/helm-charts#410]
PR: https://github.com/mongodb/helm-charts/pull/409

I would like to use pod annotations in this Helm chart which I cannot do without forking this chart or getting this PR approved.  

The intended use case is to use this for Prometheus endpoints with these annotations.  Let me know if you want me to add this as a flag as well.  

```yaml
annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
```
